import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-full flex flex-col bg-[#06080F] text-sm text-gray-200">
        <nav className="border-b border-[rgba(255,255,255,0.08)] bg-[rgba(255,255,255,0.02)] backdrop-blur-md px-6 py-3 flex items-center justify-between shrink-0">
          <div className="flex items-center gap-4">
            <h1 className="text-xl font-bold text-blue-500 tracking-wider m-0">MICROTEK</h1>
            <span className="text-xs text-gray-500 uppercase tracking-widest border-l border-gray-700 pl-4">Enterprise Fleet Ops</span>
          </div>
          <div className="flex gap-6">
            <a href="/" className="text-gray-300 hover:text-blue-400 uppercase tracking-widest text-xs font-semibold transition-colors">Fleet Operations</a>
            <a href="/analytics" className="text-gray-300 hover:text-blue-400 uppercase tracking-widest text-xs font-semibold transition-colors">Regional & Fleet Analytics</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
